apiVersion: v1
kind: Service
metadata:
  name: order-canary
  labels:
    app: order
    version: canary
spec:
  selector:
    app: order
    version: canary
  ports:
    - port: 80
      targetPort: 8003
  type: ClusterIP
